version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: indent-error-flow
        - name: range
        - name: time-naming
        - name: unexported-return
        - name: var-declaration
        - name: package-comments
  exclusions:
    generated: lax
    paths:
      - web
      - bin
